# Generated by Django 3.1.3 on 2020-11-18 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201118_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='seller_id',
        ),
    ]
