# Generated by Django 3.1.3 on 2020-11-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201118_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
